/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sven_com_apkpatchserver_DiffUtils */

#ifndef _Included_sven_com_apkpatchserver_DiffUtils
#define _Included_sven_com_apkpatchserver_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sven_com_apkpatchserver_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_sven_com_apkpatchserver_DiffUtils_genDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);




#ifdef __cplusplus
}
#endif
#endif
